version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
# hooks:
#   AfterInstall:
#     - location: scripts/after_install
#       timeout: 300
#       runas: root
#   ApplicationStart:
#     - location: scripts/start_server
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: scripts/stop_server
#       timeout: 300
#       runas: root
